services:
  stats:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./config/servers.json:/app/config/servers.json:ro
